micronaut:
  application:
    name: demo
  metrics:
    enabled: true
    export:
      datadog:
        enabled: true
        apiKey: ${DATADOG_APIKEY}
        step: PT1M
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    authentication: cookie
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
